#### breast_cancer.data Column Details


 Attribute Information: (class attribute has been moved to last column)<br>
<pre>
     Attribute                     Domain
   -- -----------------------------------------
1. Sample code number            id number
2. Clump Thickness               1 - 10
3. Uniformity of Cell Size       1 - 10
4. Uniformity of Cell Shape      1 - 10
5. Marginal Adhesion             1 - 10
6. Single Epithelial Cell Size   1 - 10
7. Bare Nuclei                   1 - 10
8. Bland Chromatin               1 - 10
9. Normal Nucleoli               1 - 10
10. Mitoses                      1 - 10
11. Class:                       (2 for benign, 4 for malignant)
</pre>

#### Classification Exercise

1) Read the dataset 'breast_cancer.data'<br>
2) Remove/handle the null values.<br>
3) Rename the column names appropritely as per the attribute info mentioned above<br>
4) Based on the general understanding of the dataset, select independent features and dependent feature<br>
5) Split the dataset into training and testing dataset with test_size 25%<br>
6) Apply Decision Tree Classification and predict the class for the test data.<br>
7) Find the confusion matrix, accuracy_score and generate classification_report.<br>
8) Apply Radom Forest Classification and predict the class for the test data.<br>
9) Find the confusion matrix, accuracy_score and generate classification_report.<br>


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/breast_cancer.data')

In [ ]:
df.head()

Sample code number  Clump Thickness  ...  Mitoses  Class
0             1002945                5  ...        1      2
1             1015425                3  ...        1      2
2             1016277                6  ...        1      2
3             1017023                4  ...        1      2
4             1017122                8  ...        1      4

[5 rows x 11 columns]

In [ ]:
df.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [ ]:
df.columns=['Sample code number','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class']

In [ ]:
df.columns

Index(['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [ ]:
df.head()

Sample code number  Clump Thickness  ...  Mitoses  Class
0             1002945                5  ...        1      2
1             1015425                3  ...        1      2
2             1016277                6  ...        1      2
3             1017023                4  ...        1      2
4             1017122                8  ...        1      4

[5 rows x 11 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['Bare Nuclei']=df['Bare Nuclei'].astype(int)
df['Bare Nuclei'].value_counts()

0     401
1     132
5      30
2      30
3      28
8      21
4      19
10     16
9       9
7       8
6       4
Name: Bare Nuclei, dtype: int64

In [ ]:
x=df.iloc[:,1:10]
y=df.iloc[:,-1]

print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(523, 9)
(523,)
(175, 9)
(175,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='gini',min_samples_split=5,max_depth=10)

In [ ]:
model.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=10, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model.score(x_test,y_test)

0.9371428571428572

In [ ]:
DT_pred=model.predict(x_test)

In [ ]:
DT_pred[:5]

array([4, 2, 2, 4, 2])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,DT_pred))

[[113   5]
 [  6  51]]


In [ ]:
print(classification_report(y_test,DT_pred))

              precision    recall  f1-score   support

           2       0.95      0.96      0.95       118
           4       0.91      0.89      0.90        57

    accuracy                           0.94       175
   macro avg       0.93      0.93      0.93       175
weighted avg       0.94      0.94      0.94       175



**Using Random** **Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(criterion='gini',min_samples_split=5,max_depth=10,n_estimators=40)

In [ ]:
RF.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
RF.score(x_test,y_test)

0.9714285714285714

In [ ]:
RF_pred=RF.predict(x_test)

In [ ]:
RF_pred[:5]

array([4, 2, 2, 4, 2])

In [ ]:
DT_pred[:5]

array([4, 2, 2, 4, 2])

In [ ]:
print(confusion_matrix(y_test,RF_pred))

[[113   5]
 [  0  57]]


In [ ]:
print(classification_report(y_test,RF_pred))

              precision    recall  f1-score   support

           2       1.00      0.96      0.98       118
           4       0.92      1.00      0.96        57

    accuracy                           0.97       175
   macro avg       0.96      0.98      0.97       175
weighted avg       0.97      0.97      0.97       175

